enableGlobalCache: true

pnpEnableInlining: true

yarnPath: .yarn/releases/yarn.js

packageExtensions:
  next@*:
    dependencies:
      "@babel/types": "*"
      "cacache": "*"
      "schema-utils": "*"
